{
    "name": "Farm Delivery Route Orders",
    "summary": "Group weekly sale.order pickings into a stock.picking.batch",
    "version": "19.0.1.0.0",
    "license": "AGPL-3",
    "author": "Ledo Enterprises, Odoo Community Association (OCA)",
    "website": "https://github.com/ledoent/farm-pack",
    "category": "Vertical/Agriculture",
    "depends": [
        "farm_base",
        "sale_management",
        "sale_stock",
        "stock",
        "stock_picking_batch",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/farm_delivery_zone_data.xml",
        "views/farm_delivery_zone_views.xml",
        "views/sale_order_views.xml",
        "views/stock_picking_batch_views.xml",
        "wizards/weekly_route_wizard_views.xml",
        "views/farm_delivery_route_menu.xml",
    ],
    "demo": [],
    "installable": True,
    "application": False,
    "development_status": "Alpha",
    "maintainers": ["dkendall"],
}
