{
    "name": "Farm Pack",
    "summary": "Umbrella: website + ordering + delivery + accounting + geo for small farms",
    "version": "19.0.1.1.0",
    "license": "AGPL-3",
    "author": "Ledo Enterprises, Odoo Community Association (OCA)",
    "website": "https://github.com/ledoent/farm-pack",
    "category": "Vertical/Agriculture",
    "depends": [
        # ledoent — internal modules (alphabetical for easy diff)
        "farm_base",
        "farm_crop",
        "farm_csa",
        # farm_csa_contract_glue is held back: odoo-addon-contract has no
        # 19.0 wheel on the OCA wheelhouse yet (versions stop at 18.0.x).
        # Re-enable when OCA publishes the 19.0 release.
        "farm_delivery_route_orders",
        "farm_delivery_routes",
        "farm_egg_production",
        "farm_fence",
        "farm_field",
        "farm_field_geo",
        "farm_field_overlays",
        "farm_harvest",
        "farm_market_event",
        "farm_market_event_website",
        "farm_observation",
        "farm_onboarding",
        "farm_planting",
        "farm_quickbooks_io",
        "farm_water_source",
        # Odoo CE — the four-jobs composition
        "account",
        "crm",
        "delivery",
        "event",
        "mass_mailing",
        "sale_management",
        "sale_stock",
        "stock_picking_batch",
        "website",
        "website_sale",
    ],
    "data": [],
    "demo": [],
    "installable": True,
    "application": True,
    "development_status": "Alpha",
    "maintainers": ["dkendall"],
}
